# -*- coding: utf-8 -*-
"""Airline passanger analysis_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6ak4h3chEIQvG7Q06jBdvGmZQjUb5YL

Import The Required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import os

"""Importing the dataset"""

df = pd.read_csv("/content/airline_passenger_satisfaction.csv")
display(df.head())

display(df.tail())

"""Detail of Dataset"""

print("The Metatdata of the dataset:",df.shape)

print("No.of rows in the dataset:",df.shape[0])

print("No.of column in the dataset",df.shape[1] )

"""All Columns of Dataset"""

df.columns

"""Column's information"""

df.info()

"""Column datatype"""

df.dtypes

"""Statictics of Dataset"""

df.describe()

"""Finding the Duplicates"""

df.duplicated().sum()

"""Finding the Nulls"""

df.isna().sum()

"""KPI Requirement"""

import pandas as pd

# Ensure df is defined by loading the dataset if it is not in locals()
if 'df' not in locals() or 'df' not in globals():
    df = pd.read_csv("/content/airline_passenger_satisfaction.csv")

## calculate total passengers
total_passengers = df["ID"].nunique()
## calculate satisfied passengers
satisfied_passengers = (df["Satisfaction"] == "Satisfied").sum()
## calaculate dissatisfied passengers
dissatisfied_passengers = (
    df["Satisfaction"] == "Neutral or Dissatisfied"
).sum()
## calculate Overall Satisfaction Rate
satisfaction_rate = (
    df["Satisfaction"].eq("Satisfied").mean() * 100
)
## calculate Dissatisfaction Rate
dissatisfaction_rate = (
    df["Satisfaction"]
    .eq("Neutral or Dissatisfied")
    .mean() * 100
)

# Display KPIs
print("Total Passengers:", total_passengers)
print("Satisfied Passengers:", satisfied_passengers)
print("Satisfaction Rate:", round(satisfaction_rate, 2), "%")
print("Dissatisfied Passengers:", dissatisfied_passengers)

"""Chart's Requirement

Passenger Satisfaction Distribution (Pie Chart)
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data
satisfaction_counts = df['Satisfaction'].value_counts()
labels = satisfaction_counts.index
sizes = satisfaction_counts.values
colors = sns.color_palette('pastel')[0:len(labels)]

# Create Pie Chart
plt.figure(figsize=(8, 6))
plt.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%',
    startangle=140,
    colors=colors,
    explode=(0.05, 0) if len(labels) > 1 else None,
    shadow=True
)

plt.title('Passenger Satisfaction Distribution', fontsize=16, fontweight='bold')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""Satisfaction by Class (Stacked Bar Chart)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df is defined
if 'df' not in locals() and 'df' not in globals():
    df = pd.read_csv('/content/airline_passenger_satisfaction.csv')

# Group data by Class and Satisfaction
class_satisfaction = pd.crosstab(df['Class'], df['Satisfaction'])

# Plotting Stacked Bar Chart
fig, ax = plt.subplots(figsize=(10, 6))
class_satisfaction.plot(
    kind='bar',
    stacked=True,
    color=sns.color_palette('pastel')[0:2],
    ax=ax,
    edgecolor='black'
)

# Customizing the visual details
plt.title('Passenger Satisfaction by Flight Class', fontsize=16, fontweight='bold')
plt.xlabel('Flight Class', fontsize=12)
plt.ylabel('Number of Passengers', fontsize=12)
plt.xticks(rotation=0)
plt.legend(title='Satisfaction', frameon=True, facecolor='white', edgecolor='black')
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Add values inside or on top of the bars
for container in ax.containers:
    ax.bar_label(container, label_type='center', fontsize=10, weight='bold')

plt.tight_layout()
plt.show()

"""Average Service Rating (Bar Chart)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df is loaded
if 'df' not in locals() and 'df' not in globals():
    df = pd.read_csv('/content/airline_passenger_satisfaction.csv')

# Identify rating-related columns (typically rated on a scale of 0-5)
rating_columns = [
    'Departure and Arrival Time Convenience',
    'Ease of Online Booking',
    'Check-in Service',
    'Online Boarding',
    'Gate Location',
    'On-board Service',
    'Seat Comfort',
    'Leg Room Service',
    'Cleanliness',
    'Food and Drink',
    'In-flight Service',
    'In-flight Wifi Service',
    'In-flight Entertainment',
    'Baggage Handling'
]

# Calculate average rating for each service and sort them
avg_ratings = df[rating_columns].mean().sort_values(ascending=False)

# Plotting Bar Chart
plt.figure(figsize=(12, 8))
sns.barplot(
    x=avg_ratings.values,
    y=avg_ratings.index,
    hue=avg_ratings.index,
    palette='viridis',
    legend=False,
    edgecolor='black'
)

# Visual enhancements
plt.title('Average Passenger Ratings by Service', fontsize=16, fontweight='bold')
plt.xlabel('Average Rating (out of 5)', fontsize=12)
plt.ylabel('Services', fontsize=12)
plt.xlim(0, 5)
plt.grid(axis='x', linestyle='--', alpha=0.5)

# Add exact values next to each bar
for index, value in enumerate(avg_ratings.values):
    plt.text(value + 0.05, index, f'{value:.2f}', va='center', fontweight='bold', fontsize=10)

plt.tight_layout()
plt.show()